# Generated by Django 4.1.6 on 2023-02-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='is_published',
            field=models.CharField(choices=[('False', 'Отсутствует'), ('True', 'В наличии'), ('needs verification', 'Требуется проверить на наличие')], default='needs verification', max_length=18),
        ),
    ]
