# Generated by Django 4.1.6 on 2023-02-09 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_location_user_remove_ad_address_ad_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.location'),
        ),
    ]
