# Generated by Django 4.1.6 on 2023-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_image_alter_ad_price_alter_location_ing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.AlterField(
            model_name='location',
            name='ing',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(),
        ),
    ]
