# Generated by Django 4.1.6 on 2023-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_ad_image_alter_location_ing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
