# Generated by Django 4.1.6 on 2023-02-13 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
