# Generated by Django 4.1.6 on 2023-02-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_alter_ad_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='category_id',
        ),
        migrations.AddField(
            model_name='ad',
            name='author_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ads.user'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.category'),
        ),
    ]
