# Generated by Django 4.1.6 on 2023-02-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_remove_ad_author_id_remove_ad_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='author_instance',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
        migrations.AddField(
            model_name='ad',
            name='author_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ads.user'),
        ),
        migrations.AddField(
            model_name='ad',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.category'),
        ),
        migrations.AlterField(
            model_name='location',
            name='ing',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True),
        ),
    ]
