# Generated by Django 4.1.6 on 2023-02-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_rename_ing_location_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_id',
            new_name='location',
        ),
    ]
