# Generated by Django 4.1.6 on 2023-02-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_rename_location_id_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='author_id',
        ),
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ads.user'),
        ),
    ]
