# Generated by Django 4.1.6 on 2023-02-14 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0020_rename_category_id_ad_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
