# Generated by Django 4.1.6 on 2023-02-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0022_alter_ad_is_published_remove_user_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='locations',
        ),
    ]
