# Generated by Django 4.1.6 on 2023-02-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rple',
            field=models.CharField(choices=[('moderator', 'moderator'), ('participant', 'participant'), ('unknown', 'unknown')], default='unknown', max_length=15),
        ),
    ]
